# application name (from appengine)
application: email-automator
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# main handlers
handlers:
- url: .*
  script: main.app

# libraries used - https://cloud.google.com/appengine/docs/python/tools/libraries27
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
