import random
import os
import re
try:
    from google.appengine.api import memcache
except ImportError:
    class _LocalMemcache(object):
        def __init__(self):
            self._store = {}

        def get(self, key):
            return self._store.get(key)

        def add(self, key, value, time=0):
            if key in self._store:
                return False
            self._store[key] = value
            return True

        def delete(self, key):
            return self._store.pop(key, None) is not None

        def clear(self):
            self._store.clear()

    memcache = _LocalMemcache()

CONFIG_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+\Z")
DEFAULT_FROM_EMAIL = "youremail@youremail.com"

def normalize_email_address(address):
    return (address or "").strip().lower()

def valid_config_email(address):
    return bool(CONFIG_EMAIL_RE.match(normalize_email_address(address)))

# these are approved users
def configured_from_users():
    configured = os.environ.get("AUTOMATION_APPROVED_SENDERS", "approveduser@approveduser.com")
    return [
        normalize_email_address(email)
        for email in configured.split(",")
        if email.strip() and valid_config_email(email)
    ]

def configured_to_email():
    email = normalize_email_address(os.environ.get("AUTOMATION_TO_EMAIL", "myemail@myemail.com"))
    if not valid_config_email(email):
        return ""
    return email

def configured_from_email():
    email = normalize_email_address(os.environ.get("AUTOMATION_FROM_EMAIL", DEFAULT_FROM_EMAIL))
    if not valid_config_email(email):
        return ""
    return email

def message_addressed_to_automation(msg, target_email=None):
    if not isinstance(msg, dict):
        return False
    if target_email is None:
        target = configured_to_email()
    else:
        target = normalize_email_address(target_email)
    if not target:
        return False

    recipients = msg.get('to') or []
    if not isinstance(recipients, (list, tuple)):
        return False

    for recipient in recipients:
        if not isinstance(recipient, (list, tuple)) or len(recipient) != 2:
            continue
        try:
            address = normalize_email_address(recipient[1])
        except AttributeError:
            continue
        if address == target:
            return True
    return False

buzz_map = [
    {"keyword": "gareth", "response": "Looks like you were emailing regarding Gareth. He loves coffee, you should consider buying him one"}
]

cheeky = ["Thanks for your note. This reply is being generated from a robot. \n\n",
          "Thanks for reaching out. I'd love to say I wrote this message, but the contents below is being generated by a robot. \n\n",
          "Hi,\n\nGreat message. Unfortunately it's just me here right now, this is Ronald (an automated robot). \n\n",
          "Hey,\n\nThanks for the message. This is Ronald the Robot, stepping in.\n\n",
          "Greetings!\n\nThis is Ronald The Robot. \n\n",
          "Hi,\n\nThis is Ronald (the robot) stepping in. \n\n",
          "Hi,\n\nThanks for your note. This is Ronald the robot. \n\n"]

unknown = ["Wow, complicated email. I'm working on a reply; if this is urgent please contact me directly.\n\n",
           "This is perplexingly difficult, but I couldn't parse your email. Let me go and grab a coffee. I'll be back soon..\n\n",
           "This is awkward. I couldn't quite parse your email to understand what this email is about. Let me get back to you soon\n\n",
           "Eeek, I couldn't figure out what your email is about. Let me get back to you as soon as I can.. (#robotfailure)\n\n"]

ending = ["Best,\nRonald The Robot\n", "Cheers,\nYour Cheeky Robot (Ronald)", "Thanks,\nRonald", "Thanks,\n Ronald The Robot", "Thanks,\nRonald\n\np.s. if you know how I can get out of here please reply.."]

WORD_RE = re.compile(r"[A-Za-z0-9_']+")
MESSAGE_ID_RE = re.compile(r"^[A-Za-z0-9._:-]+\Z")
MAX_EMAIL_BODY_LENGTH = 10000
MAX_REPLY_SUBJECT_LENGTH = 200
MAX_MESSAGE_ID_LENGTH = 128
try:
    STRING_TYPES = (basestring,)
except NameError:
    STRING_TYPES = (str,)

def text_value(value):
    if isinstance(value, STRING_TYPES):
        return value
    return ""

def bounded_email_body(txt):
    return text_value(txt)[:MAX_EMAIL_BODY_LENGTH]

def tokenize_email(txt):
    return WORD_RE.findall(bounded_email_body(txt))

def reply_subject(subject):
    normalized = " ".join(text_value(subject).splitlines()).strip()
    if len(normalized) > MAX_REPLY_SUBJECT_LENGTH:
        normalized = normalized[:MAX_REPLY_SUBJECT_LENGTH].rstrip()
    if not normalized:
        return "Re:"
    return "Re: " + normalized

def check_map(words, chooser=None):
    chooser = chooser or random.choice
    resp = ""
    for word in words:
        for buzz_word in buzz_map:
            if buzz_word['keyword'].lower() == word.lower():
                resp = buzz_word['response']
    if resp == "":
        resp = chooser(unknown)

    return chooser(cheeky) + resp + "\n\n" + chooser(ending)

def parse_email(txt, chooser=None):
    all_words = tokenize_email(txt)
    return check_map(all_words, chooser=chooser)

def normalize_message_id(msgId):
    try:
        msgId = (msgId or "").strip()
    except AttributeError:
        msgId = str(msgId).strip()
    if not msgId or len(msgId) > MAX_MESSAGE_ID_LENGTH:
        return ""
    if not MESSAGE_ID_RE.match(msgId):
        return ""
    return msgId

def gmail_message_id(summary):
    if not isinstance(summary, dict):
        return ""
    msgId = summary.get('id')
    if not isinstance(msgId, STRING_TYPES):
        return ""
    return normalize_message_id(msgId)

def cache_key(msgId):
    msgId = normalize_message_id(msgId)
    if not msgId:
        return None
    return "msg_" + msgId

def cache_check(msgId):
    key = cache_key(msgId)
    if not key:
        return False
    if memcache is None:
        return True
    data = memcache.get(key)
    if data is not None:
        return False
    else:
        return True

def reserve_message_id(msgId):
    key = cache_key(msgId)
    if not key:
        return False
    if memcache is None:
        return True
    return bool(memcache.add(key, msgId))

def release_message_id(msgId):
    key = cache_key(msgId)
    if key and memcache is not None:
        memcache.delete(key)

def approved_sender(msg):
    allowed = set(configured_from_users())
    automation_address = configured_from_email()
    senders = msg.get('from') or []
    if not isinstance(senders, (list, tuple)):
        return None
    normalized_senders = []
    for sender in senders:
        if not isinstance(sender, (list, tuple)) or len(sender) != 2:
            continue
        address = sender[1]
        try:
            normalized_address = normalize_email_address(address)
        except AttributeError:
            continue
        normalized_senders.append((normalized_address, address))

    if len(normalized_senders) != 1:
        return None

    normalized_address, address = normalized_senders[0]
    if automation_address and normalized_address == automation_address:
        return None
    if normalized_address in allowed:
        return address
    return None

def valid_email(msg, user_id):
    sender = approved_sender(msg)
    if sender is None:
        return False
    if not message_addressed_to_automation(msg):
        return False
    msgId = normalize_message_id(msg.get('msgId'))
    if msgId and reserve_message_id(msgId):
        try:
            sent = sendEmail(user_id, sender, reply_subject(msg.get('subject', "")), parse_email(msg.get('payload', "")))
        except Exception:
            release_message_id(msgId)
            raise
        if not sent:
            release_message_id(msgId)
            return False
        return True
    return False

def sendEmail(user_id, to, subject, msg):
    from_email = configured_from_email()
    if not from_email:
        return False
    # if not in cache
    # do cache check for sent email messages
    try:
        from . import send
    except (ImportError, ValueError):
        import send
    return send.SendMessage(user_id, send.CreateMessage(from_email, to, subject, msg)) is not None
