import random
import os
import re
try:
    from google.appengine.api import memcache
except ImportError:
    class _LocalMemcache(object):
        def __init__(self):
            self._store = {}

        def get(self, key):
            return self._store.get(key)

        def add(self, key, value, time=0):
            if key in self._store:
                return False
            self._store[key] = value
            return True

        def clear(self):
            self._store.clear()

    memcache = _LocalMemcache()

# set email address of user
email_address = os.environ.get("AUTOMATION_FROM_EMAIL", "youremail@youremail.com")

def normalize_email_address(address):
    return (address or "").strip().lower()

# these are approved users
def configured_from_users():
    configured = os.environ.get("AUTOMATION_APPROVED_SENDERS", "approveduser@approveduser.com")
    return [normalize_email_address(email) for email in configured.split(",") if email.strip()]

def configured_to_email():
    return normalize_email_address(os.environ.get("AUTOMATION_TO_EMAIL", "myemail@myemail.com"))

def message_addressed_to_automation(msg, target_email=None):
    if target_email is None:
        target = configured_to_email()
    else:
        target = normalize_email_address(target_email)
    if not target:
        return False

    for recipient in msg.get('to', []):
        try:
            address = recipient[1]
        except (TypeError, IndexError):
            continue
        if normalize_email_address(address) == target:
            return True
    return False

from_users = configured_from_users()

buzz_map = [
    {"keyword": "gareth", "response": "Looks like you were emailing regarding Gareth. He loves coffee, you should consider buying him one"}
]

cheeky = ["Thanks for your note. This reply is being generated from a robot. \n\n",
          "Thanks for reaching out. I'd love to say I wrote this message, but the contents below is being generated by a robot. \n\n",
          "Hi,\n\nGreat message. Unfortunately it's just me here right now, this is Ronald (an automated robot). \n\n",
          "Hey,\n\nThanks for the message. This is Ronald the Robot, stepping in.\n\n",
          "Greetings!\n\nThis is Ronald The Robot. \n\n",
          "Hi,\n\nThis is Ronald (the robot) stepping in. \n\n",
          "Hi,\n\nThanks for your note. This is Ronald the robot. \n\n"]

unknown = ["Wow, complicated email. I'm working on a reply; if this is urgent please contact me directly.\n\n",
           "This is perplexingly difficult, but I couldn't parse your email. Let me go and grab a coffee. I'll be back soon..\n\n",
           "This is awkward. I couldn't quite parse your email to understand what this email is about. Let me get back to you soon\n\n",
           "Eeek, I couldn't figure out what your email is about. Let me get back to you as soon as I can.. (#robotfailure)\n\n"]

ending = ["Best,\nRonald The Robot\n", "Cheers,\nYour Cheeky Robot (Ronald)", "Thanks,\nRonald", "Thanks,\n Ronald The Robot", "Thanks,\nRonald\n\np.s. if you know how I can get out of here please reply.."]

WORD_RE = re.compile(r"[A-Za-z0-9_']+")

def tokenize_email(txt):
    return WORD_RE.findall(txt or "")

def check_map(words, chooser=None):
    chooser = chooser or random.choice
    resp = ""
    for word in words:
        for buzz_word in buzz_map:
            if buzz_word['keyword'].lower() == word.lower():
                resp = buzz_word['response']
    if resp == "":
        resp = chooser(unknown)

    return chooser(cheeky) + resp + "\n\n" + chooser(ending)

def parse_email(txt, chooser=None):
    all_words = tokenize_email(txt)
    return check_map(all_words, chooser=chooser)

def cache_key(msgId):
    return "msg_" + str(msgId)

def cache_check(msgId):
    if not msgId:
        return False
    if memcache is None:
        return True
    data = memcache.get(cache_key(msgId))
    if data is not None:
        return False
    else:
        return True

def approved_sender(msg):
    allowed = set(normalize_email_address(email) for email in from_users)
    for name, address in msg.get('from', []):
        if normalize_email_address(address) in allowed:
            return address
    return None

def valid_email(msg, user_id):
    sender = approved_sender(msg)
    if sender is None:
        return False

    msgId = msg.get('msgId')
    if msgId and cache_check(msgId):
        sendEmail(user_id, sender, "Re: " + msg.get('subject', ""), parse_email(msg.get('payload', "")))
        if memcache is not None:
            memcache.add(cache_key(msgId), msgId)
        return True
    return False

def sendEmail(user_id, to, subject, msg):
    # if not in cache
    # do cache check for sent email messages
    try:
        from . import send
    except (ImportError, ValueError):
        import send
    send.SendMessage(user_id, send.CreateMessage(email_address, to, subject, msg))
